name: llm4mat
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.7.15
  - expat=2.7.1
  - iniconfig=2.1.0
  - libcxx=19.1.7
  - libffi=3.4.4
  - ncurses=6.5
  - openssl=3.0.17
  - packaging=25.0
  - pip=25.1
  - python=3.11.13
  - readline=8.3
  - setuptools=78.1.1
  - sqlite=3.50.2
  - tk=8.6.15
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13

  - PyMuPDF>=1.23.0

  
  - pip:
      - accelerate==1.10.1
      - annotated-types==0.7.0
      - anyio==4.10.0
      - attrs==25.3.0
      - beautifulsoup4==4.13.4
      - black==25.1.0
      - blis==0.7.11
      - cachetools==5.5.2
      - catalogue==2.0.10
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - click==8.2.1
      - cloudpathlib==0.21.1
      - confection==0.1.5
      - conllu==6.0.0
      - contourpy==1.3.3
      - coverage==7.10.6
      - cycler==0.12.1
      - cymem==2.0.11
      - dill==0.4.0
      - distro==1.9.0
      - docling==2.52.0
      - docling-core==2.48.1
      - docling-ibm-models==3.9.1
      - docling-parse==4.4.0
      - easyocr==1.7.2
      - et-xmlfile==2.0.0
      - faker==37.6.0
      - filelock==3.19.1
      - filetype==1.2.0
      - fonttools==4.59.1
      - fsspec==2025.9.0
      - google-auth==2.40.3
      - google-genai==1.36.0
      - h11==0.16.0
      - hf-xet==1.1.9
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.34.4
      - idna==3.10
      - imageio==2.37.0
      - isort==6.0.1
      - jinja2==3.1.6
      - jiter==0.10.0
      - joblib==1.5.1
      - jsonlines==3.1.0
      - jsonref==1.1.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.9
      - langcodes==3.5.0
      - language-data==1.3.0
      - latex2mathml==3.78.1
      - lazy-loader==0.4
      - lxml==5.4.0
      - marisa-trie==1.3.0
      - markdown-it-py==4.0.0
      - marko==2.2.0
      - markupsafe==3.0.2
      - matplotlib==3.10.5
      - matsci-llm-causality==0.1.0
      - mdurl==0.1.2
      - mpire==2.10.2
      - mpmath==1.3.0
      - multiprocess==0.70.18
      - murmurhash==1.0.13
      - mypy==1.17.1
      - mypy-extensions==1.1.0
      - networkx==3.5
      - ninja==1.13.0
      - nmslib-metabrainz==2.1.3
      - numpy==1.26.4
      - openai==1.107.1
      - opencv-python-headless==4.11.0.86
      - openpyxl==3.1.5
      - pandas==2.3.2
      - pathspec==0.12.1
      - pillow==11.3.0
      - platformdirs==4.4.0
      - pluggy==1.6.0
      - polyfactory==2.22.2
      - preshed==3.0.10
      - psutil==7.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pybind11==3.0.1
      - pyclipper==1.3.0.post6
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pydantic-settings==2.10.1
      - pygments==2.19.2
      - pylatexenc==2.10
      - pymupdf==1.26.4
      - pyparsing==3.2.3
      - pypdfium2==4.30.0
      - pysbd==0.3.4
      - pytest==8.4.2
      - pytest-cov==6.3.0
      - python-bidi==0.6.6
      - python-dateutil==2.9.0.post0
      - python-docx==1.2.0
      - python-dotenv==1.1.1
      - python-pptx==1.0.2
      - pytz==2025.2
      - pyyaml==6.0.2
      - referencing==0.36.2
      - regex==2025.7.34
      - requests==2.32.5
      - rich==14.1.0
      - rpds-py==0.27.1
      - rsa==4.9.1
      - rtree==1.4.1
      - ruff==0.12.12
      - safetensors==0.6.2
      - scikit-image==0.25.2
      - scikit-learn==1.7.1
      - scipy==1.16.1
      - scispacy==0.5.5
      - semchunk==2.2.2
      - shapely==2.1.1
      - shellingham==1.5.4
      - six==1.17.0
      - smart-open==7.3.0.post1
      - sniffio==1.3.1
      - soupsieve==2.7
      - spacy==3.7.5
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.5.1
      - sympy==1.14.0
      - tabulate==0.9.0
      - tenacity==9.1.2
      - thinc==8.2.5
      - threadpoolctl==3.6.0
      - tifffile==2025.9.9
      - tokenizers==0.22.0
      - torch==2.8.0
      - torchvision==0.23.0
      - tqdm==4.67.1
      - transformers==4.56.1
      - typer==0.16.1
      - typing-extensions==4.14.1
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - urllib3==2.5.0
      - wasabi==1.1.3
      - weasel==0.4.1
      - websockets==15.0.1
      - wrapt==1.17.3
      - xlsxwriter==3.2.5
prefix: /Users/gouravkumbhojkar/miniconda3/envs/llm4mat
